### PR TITLE
structure Card and CardGroup

### PR DESCRIPTION
**Pull request by alejovera**
Structure of Card and Card Container

### CODE REVIEW

**Review by maruxan — COMMENTED** [review]
Remove changes in App.js and package-lock.json

**Review by monsterkosh — APPROVED** [review]
LGTM

**Comment by monsterkosh** [comment]
> Remove changes in App.js and package-lock.json

Good call !

**Review by maruxan — APPROVED** [review]
👍

**Review by monsterkosh — APPROVED** [review]

**Pull request merged**
